const STORE="fueltrack_fitatu_v03", GOALS="fueltrack_goals_v03";
const state={rows:[],selectedDate:""};
const DEFAULT={kcal:2200,protein:180,carbs:200,fat:70};
const MICROS=[["Błonnik (g)","Błonnik","g"],["Cukry (g)","Cukry","g"],["Kwas omega 3 (g)","Omega-3","g"],["Kwas omega 6 (g)","Omega-6","g"],["Kofeina (mg)","Kofeina","mg"],["Kwas foliowy (ug)","Kwas foliowy","µg"],["Witamina A (ug)","Witamina A","µg"],["Witamina B1 (mg)","Witamina B1","mg"],["Witamina B2 (mg)","Witamina B2","mg"],["Witamina B6 (mg)","Witamina B6","mg"],["Witamina B12 (ug)","Witamina B12","µg"],["Witamina C (mg)","Witamina C","mg"],["Witamina D (ug)","Witamina D","µg"],["Witamina E (mg)","Witamina E","mg"],["Witamina PP (mg)","Witamina PP","mg"],["Witamina K (ug)","Witamina K","µg"],["Cynk (mg)","Cynk","mg"],["Fosfor (mg)","Fosfor","mg"],["Jod (ug)","Jod","µg"],["Magnez (mg)","Magnez","mg"],["Potas (mg)","Potas","mg"],["Selen (ug)","Selen","µg"],["Sód (mg)","Sód","mg"],["Wapń (mg)","Wapń","mg"],["Żelazo (mg)","Żelazo","mg"],["Sól (g)","Sól","g"],["Cholesterol (mg)","Cholesterol","mg"],["Nasycone (g)","Kwasy nasycone","g"]];
const $=id=>document.getElementById(id);
const num=v=>{let n=parseFloat(String(v??"").replace(",","."));return Number.isFinite(n)?n:0};
const fmt=v=>Number(v||0).toLocaleString("pl-PL",{maximumFractionDigits:2});
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function status(m,e=false){$("status").textContent=m;$("status").classList.remove("hidden","error");if(e)$("status").classList.add("error");setTimeout(()=>$("status").classList.add("hidden"),5000)}
function csv(text){text=text.replace(/^\uFEFF/,"");let a=[],r=[],c="",q=false;for(let i=0;i<text.length;i++){let x=text[i],n=text[i+1];if(x=='"'){if(q&&n=='"'){c+='"';i++}else q=!q}else if(x==","&&!q){r.push(c);c=""}else if((x=="\n"||x=="\r")&&!q){if(x=="\r"&&n=="\n")i++;r.push(c);c="";if(r.some(v=>v.trim()))a.push(r);r=[]}else c+=x}if(c||r.length){r.push(c);if(r.some(v=>v.trim()))a.push(r)}if(!a.length)return[];let h=a[0].map(x=>x.trim());return a.slice(1).map(v=>Object.fromEntries(h.map((k,i)=>[k,(v[i]??"").trim()]))).filter(o=>Object.values(o).some(Boolean))}
function load(){try{state.rows=JSON.parse(localStorage.getItem(STORE)||"[]")}catch{state.rows=[]}if(!state.rows.length)try{let old=JSON.parse(localStorage.getItem("fueltrack_fitatu_v02")||"[]");if(old.length){state.rows=old;save()}}catch{}}
function save(){localStorage.setItem(STORE,JSON.stringify(state.rows))}
function goals(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem(GOALS)||"{}")}}catch{return {...DEFAULT}}}
function dates(){return [...new Set(state.rows.map(r=>r["Data"]).filter(Boolean))].sort().reverse()}
function total(d){let rs=state.rows.filter(r=>r["Data"]===d),t={"kalorie (kcal)":0,"Białka (g)":0,"Węglowodany (g)":0,"Tłuszcze (g)":0};rs.forEach(r=>{t["kalorie (kcal)"]+=num(r["kalorie (kcal)"]);t["Białka (g)"]+=num(r["Białka (g)"]);t["Węglowodany (g)"]+=num(r["Węglowodany (g)"]);t["Tłuszcze (g)"]+=num(r["Tłuszcze (g)"])});MICROS.forEach(([k])=>t[k]=rs.reduce((s,r)=>s+num(r[k]),0));return t}
function renderDates(){let ds=dates();if(!ds.length){state.selectedDate="";$("selectedDateLabel").textContent="Brak danych";$("dateSelect").innerHTML="";$("dayCount").textContent="0 dni";return}if(!ds.includes(state.selectedDate))state.selectedDate=ds[0];$("dateSelect").innerHTML=ds.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join("");$("dateSelect").value=state.selectedDate;$("selectedDateLabel").textContent=state.selectedDate;$("dayCount").textContent=`${ds.length} ${ds.length==1?"dzień":"dni"}`}
function renderDay(){if(!state.selectedDate)return;let rs=state.rows.filter(r=>r["Data"]===state.selectedDate),t=total(state.selectedDate);$("kcal").textContent=fmt(t["kalorie (kcal)"]);$("protein").textContent=fmt(t["Białka (g)"]);$("carbs").textContent=fmt(t["Węglowodany (g)"]);$("fat").textContent=fmt(t["Tłuszcze (g)"]);let ms={};rs.forEach(r=>(ms[r["Posiłek"]||"Inne"]??=[]).push(r));$("meals").innerHTML=Object.entries(ms).map(([m,rr])=>`<div class="meal"><div class="meal-title">${esc(m)}</div>${rr.map(r=>`<div class="product"><b>${esc(r["Produkty i potrawy"]||"Produkt")}</b><div class="product-meta">${esc(r["Miara użyteczna"]||"")} · ${fmt(num(r["ilość (g)"]))} g · ${fmt(num(r["kalorie (kcal)"]))} kcal · B ${fmt(num(r["Białka (g)"]))} · W ${fmt(num(r["Węglowodany (g)"]))} · T ${fmt(num(r["Tłuszcze (g)"]))}</div></div>`).join("")}</div>`).join("");$("micros").innerHTML=MICROS.map(([k,l,u])=>`<div class="micro"><b>${fmt(t[k])} ${u}</b><span>${l}</span></div>`).join("")}
function renderHistory(){$("history").innerHTML=dates().map(d=>`<div class="history-row"><button data-date="${esc(d)}">${esc(d)}</button><span>${fmt(total(d)["kalorie (kcal)"])} kcal</span></div>`).join("");document.querySelectorAll("[data-date]").forEach(b=>b.onclick=()=>{state.selectedDate=b.dataset.date;renderAll();scrollTo({top:0,behavior:"smooth"})})}
function renderGoals(){let g=goals(),box=$("goalsBox");if(!box){box=document.createElement("section");box.id="goalsBox";box.className="card";box.innerHTML=`<div class="section-head"><h2>Cele dzienne</h2></div><div class="micro-grid"><label class="micro">Kcal<input id="goalKcal" type="number" min="0"></label><label class="micro">Białko (g)<input id="goalProtein" type="number" min="0"></label><label class="micro">Węglowodany (g)<input id="goalCarbs" type="number" min="0"></label><label class="micro">Tłuszcz (g)<input id="goalFat" type="number" min="0"></label></div><button id="saveGoals" class="secondary" style="margin-top:12px">Zapisz cele</button><div id="goalSummary" style="margin-top:14px"></div>`;document.querySelector(".app").insertBefore(box,document.querySelector("footer"));$("saveGoals").onclick=()=>{localStorage.setItem(GOALS,JSON.stringify({kcal:num($("goalKcal").value),protein:num($("goalProtein").value),carbs:num($("goalCarbs").value),fat:num($("goalFat").value)}));renderAll();status("Cele zapisane.")}}$("goalKcal").value=g.kcal;$("goalProtein").value=g.protein;$("goalCarbs").value=g.carbs;$("goalFat").value=g.fat;if(state.selectedDate){let t=total(state.selectedDate);$("goalSummary").innerHTML=`<div class="micro"><b>${fmt(t["kalorie (kcal)"])} / ${fmt(g.kcal)} kcal</b><span>Bilans: ${fmt(t["kalorie (kcal)"]-g.kcal)} kcal</span></div><div class="micro" style="margin-top:8px"><b>Białko ${fmt(t["Białka (g)"])} / ${fmt(g.protein)} g</b><span>Bilans: ${fmt(t["Białka (g)"]-g.protein)} g</span></div><div class="micro" style="margin-top:8px"><b>Węglowodany ${fmt(t["Węglowodany (g)"])} / ${fmt(g.carbs)} g</b><span>Bilans: ${fmt(t["Węglowodany (g)"]-g.carbs)} g</span></div><div class="micro" style="margin-top:8px"><b>Tłuszcz ${fmt(t["Tłuszcze (g)"])} / ${fmt(g.fat)} g</b><span>Bilans: ${fmt(t["Tłuszcze (g)"]-g.fat)} g</span></div>`}}
function report(d){let rs=state.rows.filter(r=>r["Data"]===d),t=total(d),ms={};rs.forEach(r=>(ms[r["Posiłek"]||"Inne"]??=[]).push(r));let s=`FUELTRACK AI — RAPORT ŻYWIENIA\nDATA: ${d}\n\n`;for(let[m,rr]of Object.entries(ms)){s+=m.toUpperCase()+"\n";rr.forEach(r=>s+=`• ${r["Produkty i potrawy"]||"Produkt"} — ${r["ilość (g)"]||"?"} g — ${fmt(num(r["kalorie (kcal)"]))} kcal | B ${fmt(num(r["Białka (g)"]))} g | W ${fmt(num(r["Węglowodany (g)"]))} g | T ${fmt(num(r["Tłuszcze (g)"]))} g\n`);s+="\n"}let g=goals();s+=`PODSUMOWANIE\nKalorie: ${fmt(t["kalorie (kcal)"])} kcal\nBiałko: ${fmt(t["Białka (g)"])} g\nWęglowodany: ${fmt(t["Węglowodany (g)"])} g\nTłuszcz: ${fmt(t["Tłuszcze (g)"])} g\n\nCEL / BILANS\nKalorie: ${fmt(t["kalorie (kcal)"]-g.kcal)} kcal\nBiałko: ${fmt(t["Białka (g)"]-g.protein)} g\nWęglowodany: ${fmt(t["Węglowodany (g)"]-g.carbs)} g\nTłuszcz: ${fmt(t["Tłuszcze (g)"]-g.fat)} g\n\nMIKRO I POZOSTAŁE SKŁADNIKI\n`;MICROS.forEach(([k,l,u])=>{if(t[k])s+=`${l}: ${fmt(t[k])} ${u}\n`});return s}
async function copyReport(){if(!state.selectedDate)return status("Najpierw zaimportuj dane z Fitatu.",true);let s=report(state.selectedDate);try{await navigator.clipboard.writeText(s)}catch{let x=document.createElement("textarea");x.value=s;document.body.appendChild(x);x.select();document.execCommand("copy");x.remove()}status("Raport skopiowany do schowka.")}
function merge(rows,replace){let inc=[...new Set(rows.map(r=>r["Data"]).filter(Boolean))],rep=new Set(replace),kept=state.rows.filter(r=>!inc.includes(r["Data"])||!rep.has(r["Data"])),existing=new Set(kept.map(r=>r["Data"])),add=rows.filter(r=>rep.has(r["Data"])||!existing.has(r["Data"]));state.rows=[...kept,...add];save();state.selectedDate=getDates()[0]||"";renderAll();status(`Import zakończony. Baza zawiera ${getDates().length} dni.`)}
$("importBtn").onclick=()=>$("fileInput").click();
$("fileInput").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let rows=csv(await f.text());if(!rows.length)throw Error("Nie udało się odczytać CSV.");let req=["Data","Posiłek","Produkty i potrawy","kalorie (kcal)","Białka (g)"],miss=req.filter(k=>!(k in rows[0]));if(miss.length)throw Error("Brakuje kolumn Fitatu: "+miss.join(", "));let inc=[...new Set(rows.map(r=>r["Data"]).filter(Boolean))],existing=new Set(dates()),conf=inc.filter(d=>existing.has(d)),newD=inc.filter(d=>!existing.has(d));if(conf.length){let replace=confirm(`Import: ${inc.length} dni.\nNowe: ${newD.length}\nJuż zapisane: ${conf.length}\n\nOK = ZASTĄP istniejące dni\nAnuluj = POMIŃ istniejące dni`);merge(rows,replace?conf:[])}else merge(rows,[])}catch(err){status(err.message||"Błąd importu.",true)}e.target.value=""};
$("dateSelect").onchange=e=>{state.selectedDate=e.target.value;renderAll()};$("copyBtn").onclick=copyReport;
function renderAll(){renderDates();renderDay();renderHistory();renderGoals()}load();renderAll();
